name: craete pull request to new branch
on: create

jobs:
    pull-request:
        name: Open PR to main
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v3
            - name: pull-request
              uses: repo-sync/pull-request@v2
              with: 
                destination_branch: "main"
                pr_title: "Pulling ${{ github.ref }} into main"
                pr_body: "*Automated PR*"
                pr_draft: true
                github_token: ${{ secrets.GITHUB_TOKEN }}