name: pipeline
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: install pip requirments.txt
        run: pip install -r App/requirements.txt
      - name: run unittest
        run: python3 -m unittest discover App/test
